language: 'python'
python:
  - '3.5.2'
install:
  - pip install -r requirements.txt
env:
  - DB = postgres USER = postgres PASSWORD = '123'
before_script:
  - psql -c "CREATE DATABASE store;" -U postgres
  - export SECRET_KEY="NOCSNDOCNnocnsodi"

script:
  - pytest -v --cov=app/api
  - coveralls
after_success:
  - coveralls