language: python
python:
  - "3.6"

# command to install dependencies
install:
 - pip install -r requirements.txt
 - pip install coverage codev
 - pip install nose
before_script:
 - psql -c ‘create database store;’ -U postgres
# Run tests
script:
- nosetests --exe --with-coverage --cover-package=app
after_success:
 - coveralls
