language: 'python'
python:
  - '3.5.2'
install:
  - pip install -r requirements.txt
before_script:
 - export DB_NAME="store"
 - psql -c 'create database store;' -U postgres

script:
  - pytest -v --cov=app/api
  - coveralls
after_success:
  - coveralls