language: python
python:
   - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage codev
  - pip install nose

services:
  - postgresql

before_script:
  - psql -c 'create database store_manager;' -U postgres
env:
  - DATABASE_URL="dbname='store' user='postgres' host='localhost' port=5432 password=''"

# Run tests
script:
    - nosetests --with-coverage --cover-package=app && coverage report
    - coveralls

after_success:
  - coveralls