language: python
python:
   - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage codev
  - pip install nose

services:
  - postgresql

before_script:
  - psql -c 'create database store;' -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD '123';" -U postgres
env:
  - DATABASE_URL="database='store', user='postgres', password='123', port='5432'"


# Run tests
script:
    - nosetests --with-coverage --cover-package=app && coverage report
    - coveralls

after_success:
  - coveralls